Implemented a decent amount of the translation use case [See desc]
jaronfernandes/InfoLingo pull request #19
Opened 2023-11-07 09:33 UTC by jaronfernandes

Completed a sizeable amount of the translation use-case, with the exception of:
- Hooking use case up with the View
- Extensive testing with the API, trying to find edge cases
- Displaying it to the View.

2023-11-09 02:18 UTC, Jaiz183 requested changes
I think you shouldn't merge your branch right now. As we learnt recently, pull requests are primarily made when you complete a feature, not when you are in an intermediate stage. If you need to make smaller features, make sub-branches and merge onto this branch. When you're ready with the translation use case, I'll approve the PR. Regardless, your changes look good so far, apart from some violated coding conventions (Javadocs, try-catch statements). Good attention to detail to catch mistakes like non-private fields.

2023-11-09 05:25 UTC, jaronfernandes commented
> I think you shouldn't merge your branch right now. If you need to make smaller features, make sub-branches.

Gotcha, that's a good idea. I'll create a PR when the whole use-case is ready.

2023-11-09 05:25 UTC, closed without merging

2023-12-06 15:52 UTC, Jaiz183 commented on src/app/TranslationUseCaseFactory.java
> +public class TranslationUseCaseFactory {
You should write Javadocs for this class.

2023-12-06 15:53 UTC, Jaiz183 commented on src/data_access/APIDataAccessObject.java
> +        try {
You should use try-catch statements around smaller blocks of code. This statement could catch errors in deserialisation, decoding or request sending.

2023-12-06 15:54 UTC, Jaiz183 commented on src/view/HomeView.java
> +    private ArticleRetrievalController articleRetrievalController;
Good job with noticing the non-private instance attribute!